# Generated by Django 3.0.5 on 2020-04-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
